version: '3.1'

services:
  db:
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MJ_MONGODB_DBNAME}
      MONGO_INITDB_ROOT_USERNAME: ${MJ_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MJ_MONGODB_PASSWORD}
    volumes:
      - ${MJ_MONGODB_DATA}:/data/db
    expose:
      - 27017
    ports:
      - ${MJ_MONGODB_PORT}:27017

  app:
    image: maven:3.8-openjdk-17-slim
    restart: always
    environment:
      MJ_DB_HOST: db
      MJ_DB_PORT: 27017
      MJ_DB_AUTH_DB: ${MJ_MONGODB_AUTH_DB}
      MJ_DB_NAME: ${MJ_MONGODB_NAME}
      MJ_DB_USER: ${MJ_MONGODB_USER}
      MJ_DB_PASSWORD: ${MJ_MONGODB_PASSWORD}
    depends_on:
      - db
    command: mvn spring-boot:run -Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - .:/usr/src/mymaven
      - ~/.m2:/root/.m2
    working_dir: /usr/src/mymaven
    expose:
      - 8080
      - 5005
    ports:
      - ${MJ_API_BACKEND_PORT}:8080
      - ${MJ_API_DEBUG_PORT}:5005
