application-version: @project.version@
server:
  port: 8080

spring:
  data:
    mongodb:
      host: ${MJ_DB_HOST:localhost}
      port: ${MJ_DB_PORT:27017}
      authentication-database: ${MJ_DB_AUTH_DB:admin}
      database: ${MJ_DB_DATABASE:APITests}
      username: ${MJ_DB_USER:api}
      password: ${MJ_DB_PASSWORD:api}

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER